spring.application.name=hiber
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=715264

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080